// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'es'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * H​e​l​l​o​ ​{​n​a​m​e​}​!
	 * @param {unknown} name
	 */
	HI: RequiredParams<'name'>
	/**
	 * S​o​c​i​a​l​ ​A​c​t​i​o​n
	 */
	TITLE: string
}

export type TranslationFunctions = {
	/**
	 * Hello {name}!
	 */
	HI: (arg: { name: unknown }) => LocalizedString
	/**
	 * Social Action
	 */
	TITLE: () => LocalizedString
}

export type Formatters = {}
